language: go
go:
  - 1.x
install:
  - go build -v ./...

script:
  - echo "" > coverage.txt
  - sh test.sh

after_success:
  - test $TRAVIS_BRANCH = "master" && 
    bash <(curl -s https://codecov.io/bash)
